# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/165eElbq6scMtx10d9z_LQmr2xD96Di23
"""

!pip install streamlit -q
!pip install pyngrok -q

from google.colab import files
uploaded = files.upload()

import zipfile

with zipfile.ZipFile("archive (2).zip", 'r') as zip_ref:
    zip_ref.extractall("data")

import os
os.listdir("data")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns
# 
# st.title("Delhi NCR Property Dashboard")
# 
# df = pd.read_csv("data/real_estate_main.csv")
# df.columns = df.columns.str.lower().str.strip()
# 
# df = df.rename(columns={
#     'total_area':'area',
#     'bedroom':'bhk'
# })
# 
# df = df[['location','area','bhk','bathroom','price']]
# df = df.dropna()
# 
# st.subheader("Dataset")
# st.dataframe(df.head())
# 
# # KPI
# col1,col2,col3 = st.columns(3)
# 
# col1.metric("Listings", len(df))
# col2.metric("Avg Price", round(df['price'].mean(),2))
# col3.metric("Avg Area", round(df['area'].mean(),2))
# 
# # Histogram
# st.subheader("Price Distribution")
# 
# fig,ax=plt.subplots()
# 
# sns.histplot(df['price'],bins=30,ax=ax)
# 
# st.pyplot(fig)
# 
# # Heatmap
# st.subheader("Correlation Heatmap")
# 
# fig,ax=plt.subplots()
# 
# sns.heatmap(
#     df.corr(numeric_only=True),
#     annot=True,
#     cmap='coolwarm',
#     ax=ax
# )
# 
# st.pyplot(fig)

!streamlit run app.py &>/content/logs.txt &

!streamlit run app.py &>/content/logs.txt &

from pyngrok import ngrok

ngrok.set_auth_token("3Dwh2E122aayq1kOGjQCGSxf73u_Kn8tZ3mgpve7fsV6DY1Q")

!streamlit run app.py &>/content/logs.txt &

public_url = ngrok.connect(8501)
print(public_url)

